export const appStyles = {
  actionRow: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 2,
  },
  body: {
    color: "#3f3f46",
    fontSize: 16,
    lineHeight: 22,
    marginTop: 10,
  },
  button: {
    alignItems: "center",
    backgroundColor: "#0f766e",
    minHeight: 48,
    justifyContent: "center",
    marginTop: 12,
    paddingHorizontal: 18,
  },
  buttonDisabled: {
    alignItems: "center",
    backgroundColor: "#a1a1aa",
    minHeight: 48,
    justifyContent: "center",
    marginTop: 12,
    paddingHorizontal: 18,
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  content: {
    padding: 20,
  },
  confirmation: {
    borderColor: "#d97706",
    borderWidth: 1,
    marginTop: 12,
    minHeight: 48,
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  confirmationActive: {
    backgroundColor: "#d97706",
    borderColor: "#d97706",
    borderWidth: 1,
    marginTop: 12,
    minHeight: 48,
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  confirmationActiveText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
  },
  confirmationText: {
    color: "#92400e",
    fontSize: 16,
    fontWeight: "800",
  },
  eyebrow: {
    color: "#0f766e",
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  input: {
    borderColor: "#d4d4d8",
    borderWidth: 1,
    color: "#18181b",
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  label: {
    color: "#18181b",
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 6,
  },
  labelSpaced: {
    color: "#18181b",
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 6,
    marginTop: 12,
  },
  jobCard: {
    borderColor: "#d4d4d8",
    borderWidth: 1,
    marginTop: 14,
    padding: 14,
  },
  jobDeparture: {
    color: "#18181b",
    fontSize: 18,
    fontWeight: "800",
    marginTop: 6,
  },
  jobMetaGrid: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  jobMetaItem: {
    borderColor: "#e4e4e7",
    borderWidth: 1,
    minWidth: 130,
    padding: 8,
  },
  jobRegion: {
    color: "#0f766e",
    fontSize: 22,
    fontWeight: "900",
  },
  jobTitle: {
    color: "#18181b",
    fontSize: 18,
    fontWeight: "800",
    marginTop: 4,
  },
  meta: {
    color: "#71717a",
    fontSize: 12,
    marginTop: 6,
  },
  metaLabel: {
    color: "#71717a",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  metaValue: {
    color: "#18181b",
    fontSize: 15,
    fontWeight: "700",
    marginTop: 3,
  },
  mono: {
    color: "#18181b",
    fontFamily: "monospace",
    fontSize: 14,
  },
  noticeError: {
    backgroundColor: "#fef2f2",
    borderColor: "#fecaca",
    borderWidth: 1,
    marginTop: 12,
    padding: 12,
  },
  noticeMessage: {
    color: "#3f3f46",
    fontSize: 15,
    marginTop: 4,
  },
  noticeOk: {
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
    borderWidth: 1,
    marginTop: 12,
    padding: 12,
  },
  noticeTitle: {
    color: "#18181b",
    fontSize: 17,
    fontWeight: "800",
  },
  noticeWarn: {
    backgroundColor: "#fffbeb",
    borderColor: "#fde68a",
    borderWidth: 1,
    marginTop: 12,
    padding: 12,
  },
  queueItem: {
    borderColor: "#e4e4e7",
    borderWidth: 1,
    marginTop: 10,
    padding: 10,
  },
  screen: {
    backgroundColor: "#f4f4f5",
    flex: 1,
  },
  section: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderWidth: 1,
    marginTop: 18,
    padding: 14,
  },
  sectionTitle: {
    color: "#18181b",
    fontSize: 20,
    fontWeight: "800",
    marginBottom: 12,
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: "#0f766e",
    borderWidth: 1,
    justifyContent: "center",
    marginTop: 12,
    minHeight: 48,
    paddingHorizontal: 18,
  },
  secondaryButtonText: {
    color: "#0f766e",
    fontSize: 16,
    fontWeight: "700",
  },
  statusError: {
    color: "#b91c1c",
    fontSize: 18,
    fontWeight: "800",
  },
  statusMessage: {
    color: "#3f3f46",
    fontSize: 15,
    marginTop: 6,
  },
  statusOk: {
    color: "#047857",
    fontSize: 18,
    fontWeight: "800",
  },
  statusPanel: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderWidth: 1,
    marginTop: 18,
    padding: 14,
  },
  textArea: {
    borderColor: "#d4d4d8",
    borderWidth: 1,
    color: "#18181b",
    fontSize: 16,
    minHeight: 92,
    paddingHorizontal: 12,
    paddingVertical: 10,
    textAlignVertical: "top",
  },
  title: {
    color: "#18181b",
    fontSize: 30,
    fontWeight: "800",
    marginTop: 4,
  },
  userName: {
    color: "#18181b",
    fontSize: 18,
    fontWeight: "800",
  },
  userPanel: {
    borderColor: "#e4e4e7",
    borderWidth: 1,
    marginBottom: 12,
    padding: 12,
  },
} as const;
