export const DEFAULT_NATIVE_ACCESS_TOKEN_EXPIRES_IN_SECONDS = 15 * 60;
export const DEFAULT_NATIVE_SESSION_IDLE_EXPIRES_IN_SECONDS =
  400 * 24 * 60 * 60;
export const DEFAULT_NATIVE_SESSION_ABSOLUTE_EXPIRES_IN_SECONDS =
  5 * 365 * 24 * 60 * 60;
export const DEFAULT_NATIVE_REFRESH_RATE_LIMIT_MAX = 10;
export const DEFAULT_NATIVE_REFRESH_RATE_LIMIT_WINDOW_SECONDS = 60;
